-- ⚠️ זה רק לבדיקה! לא לייצור!
-- Disable RLS temporarily for testing

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE exercise_library DISABLE ROW LEVEL SECURITY;
ALTER TABLE workout_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE routines DISABLE ROW LEVEL SECURITY;
ALTER TABLE routine_exercises DISABLE ROW LEVEL SECURITY;
ALTER TABLE workout_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE set_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE nutrition_swaps DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_nutrition_logs DISABLE ROW LEVEL SECURITY;

